// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM84hN8oRoBhQyK1Qqz03F1-quO-VivvE',
    appId: '1:795525687269:web:821b62679486803a29710c',
    messagingSenderId: '795525687269',
    projectId: 'aptoparati-782b9',
    authDomain: 'aptoparati-782b9.firebaseapp.com',
    storageBucket: 'aptoparati-782b9.firebasestorage.app',
    measurementId: 'G-QWE1YBMQZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqR0HFffRmzwCJFL_coHAQ3NDcZc4t8k',
    appId: '1:795525687269:android:668f0c5047bb690029710c',
    messagingSenderId: '795525687269',
    projectId: 'aptoparati-782b9',
    storageBucket: 'aptoparati-782b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBanhW60fpUsYNTQfIA4BEp89fM92VP_nA',
    appId: '1:795525687269:ios:a58e28a7f954c3dd29710c',
    messagingSenderId: '795525687269',
    projectId: 'aptoparati-782b9',
    storageBucket: 'aptoparati-782b9.firebasestorage.app',
    iosClientId: '795525687269-gdj8gtqrd404ra0peonb60lng3o1cnvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptoparati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBanhW60fpUsYNTQfIA4BEp89fM92VP_nA',
    appId: '1:795525687269:ios:a58e28a7f954c3dd29710c',
    messagingSenderId: '795525687269',
    projectId: 'aptoparati-782b9',
    storageBucket: 'aptoparati-782b9.firebasestorage.app',
    iosClientId: '795525687269-gdj8gtqrd404ra0peonb60lng3o1cnvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptoparati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM84hN8oRoBhQyK1Qqz03F1-quO-VivvE',
    appId: '1:795525687269:web:1f9709a9cdc46ad129710c',
    messagingSenderId: '795525687269',
    projectId: 'aptoparati-782b9',
    authDomain: 'aptoparati-782b9.firebaseapp.com',
    storageBucket: 'aptoparati-782b9.firebasestorage.app',
    measurementId: 'G-SGQPTL7RYN',
  );
}
